[theme]
base = "light"
primaryColor = "#88749F"
backgroundColor = "#F7F6F3"
secondaryBackgroundColor = "#EEEBF3"
textColor = "#38485D"
font = "sans serif"

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
